### PR TITLE
Use different language and addresses

### PR DESCRIPTION
**Pull request by JoshuaBehrens**
Sooo this is my work on supporting Visa / Carte Bancaire in my project. I have questions. First to my changes. The way how you currently access the language is only working in the unit tests as the unit tests use a mock that is too far away from the real scenario as the mock knows which locale it works with and the real scenario never sets the requests locale and therefore will always fallback to `en`. There is an other issue. Carte Bancaire is a French Visa variant and therefore needs to have the locale `fr_FR` later in the process. Even with the right locale in the request `getTranslatedLocale` will never return `fr_FR` so we still get Visa with the Generic Payment. So in this case I now use the language that has been used by the user to use the webpage. Still not perfect but more reliable.

While I dived into the code and changed the above mentioned parts I also noticed you are transfering the customers default addresses. These are very easy to access but unreliable. They are very likely to work out for persons who will rush through the checkout. Anyone who might use a new and different billing address throughout the checkout process can cause wrong data be transfered to your API. I corrected it to send the data of the order that is connected to that transaction. Be aware I made the choice to send no shipping data when no shipping information is given. This is highly unlikely but data structure from shopware allows it.

I admit, I tested it as a patch in my composer's vendor folder and it worked for me quite well. I see that I broke test code but I am unsure whether I am rewriting the tests correctly to match my changes. This is where I would like to have comments from your side.

Now I have a question reaching further out of the bounds of my change. Visa / Carte Bancaire is a French service. Why is the usage depending on a value (the locale) that is also used elsewhere in the world? So first the locale is not source I want to trust when I want to control behaviour on a regional service. Second depending on the browser request locale will definitely be different from the usage in the shop (Which presumably will enable Visa / Carte Bancaire only when billing address is France). This is very confusing to me why this approach has been used as solution and I would like to understand it a bit more as I am quite unfamiliar with branded Visa services.

### CODE REVIEW

**Comment by JoshuaBehrens** [comment]
I discussed with my team and I add a second commit to change the locale to include the billing country iso so we can be sure that the right country is used in the right language. This adds a whole lot of complexity though.

**Comment by mikededecker1** [comment]
Hi,

We are currently checking out your pull request regarding the default address and the wrong locale being returned. We will keep you updated on it.

Regarding the unreliability for showing Carte Bancaire based on locale instead of the country. This is something we will suggest to the API developers team.

**Comment by JoshuaBehrens** [comment]
It is me 👋 Any progress you can share? 😃

**Comment by mikededecker1** [comment]
We have reviewed your code and we have come to the following.

The problem with the locale should be resolved in version 2.5.0. But the issue with the default address isn't resolved yet. This is because we can't reproduce the issue. Could you send us the steps to reproduce this issue

**Comment by JoshuaBehrens** [comment]
I just wanted to create a test shop to record a client-independant clip. For the test account I have to accept a box in the registration form that states

> I am an authorised representative and have the legal authority to act and sign on behalf of the company.

This would mean basically only C*O/procurist can create a test account? Why do I have to confirm that on testmerchant.multisafepay.com anyway?

**Comment by Jasper-MultiSafepay** [comment]
You can just ignore that part.
I have asked internally to remove that from the registration form, as a test account is just for testing.
Please let us know if you have any other issues or can reproduce this issue.
The issue with the default address is not reproducible for us.
When we add and use a new address as a billing address, this is correctly picked up by the plugin.

**Comment by JoshuaBehrens** [comment]
Thanks for the info, I will check again

**Comment by JoshuaBehrens** [comment]
I used a test shop, created a test account and setup mastercard. In the following video you can see me ordering with a "German" address and complete. I show the order in shopware admin and msp admin. Then I repeat the order but I won't complete in the msp payment screen. I cancel, change my customers default addresses to a "Japanese" one and a "British" one and finish my previous order. I show the second order in shopware and it still holds the previous German address I used when I placed my order (before paying) and I show the same order in the msp admin that will use my previously changed address.

https://user-images.githubusercontent.com/1133593/145659307-fa8f2ac4-012a-4ff0-901a-55cedb6f90ae.mp4

**Comment by mikededecker1** [comment]
Hi,

Thank you for the mp4 file. this way we could easily identify and fix the problem.

We have created a separate branch with this fix (https://github.com/MultiSafepay/shopware6/tree/PLGSHPS6-260-use-correct-billing-shipping-address), and we hope that you can check those changes if they resolve your issue and if needed give feedback on it.

**Comment by JoshuaBehrens** [comment]
I can have a look at it :)

**Comment by JoshuaBehrens** [comment]
Hi @Mike-MultiSafepay I had a look into it. It works in my clean test shop. As I would like to install this update into an shop with a older shopware version I tested it in there as well and I run into this:

grafik

This also explains why I chose the way I implement it my way: I load the missing addresses to support my older shopware version (6.3).

When you look into this as well we are fine :)

**Comment by mikededecker1** [comment]
Hi @JoshuaBehrens

Sorry for getting back to you so late, this ticket got off my radar.

I can see what the issue is and I'm currently working on adding support for version 6.4 and 6.3 .

I will send you a new patch when I have the patch ready

**Comment by JoshuaBehrens** [comment]
Great to read about the awareness and progress @Mike-MultiSafepay :)

**Comment by mikededecker1** [comment]
Hi,

We have updated the branch that contained the previous fix for this issue. with this update we will now get the data from the database if the base object doesn't contain the needed data. This will fix the `getStreet() on null` error.

If you have the time can you test it and if needed, give feedback on it.

**Comment by mikededecker1** [comment]
Hi @JoshuaBehrens ,

We just released a new version of our plugin. this version contains the fix for getting the address data from the order instead of the default address. Hopefully this releases solves your issue. if not, don't hesitate to reopen this PR/Issue

**Comment by JoshuaBehrens** [comment]
Sorry for not coming back to you in a reasonable time frame. Let's see whether it will help us :)

**Pull request closed without merging**
